const stages=[
{name:'웨이퍼 제조',tag:'INGOT',desc:'실리콘 잉곳을 아주 얇고 정확하게 썰어 웨이퍼를 만들어 봐.',type:'slice'},
{name:'산화',tag:'OXIDIZE',desc:'산화로의 온도를 알맞게 맞추면 웨이퍼 표면에 균일한 산화막이 생겨.',type:'tune'},
{name:'포토',tag:'PHOTO',desc:'빛을 통과시킬 마스크의 패턴을 골라 감광액 위에 회로 모양을 찍어 봐.',type:'pattern'},
{name:'식각',tag:'ETCH',desc:'보호막이 없는 칸만 골라 불필요한 부분을 제거해. 필요한 칸을 모두 찾아야 해.',type:'etch'},
{name:'증착·이온주입',tag:'LAYER',desc:'양쪽 원자 공급량을 균형 있게 맞춰 단단하고 균일한 박막을 만들어 봐.',type:'balance'},
{name:'금속 배선',tag:'CONNECT',desc:'흩어진 접점을 올바른 순서로 연결해 전류가 흐르는 길을 완성해.',type:'connect'},
{name:'EDS',tag:'TEST',desc:'검사 결과 카드를 읽고 정상 다이와 불량 다이를 분류해 봐.',type:'sort'},
{name:'패키징',tag:'PACK',desc:'칩 부품을 알맞은 위치에 배치해 외부 충격을 견디는 패키지를 완성해.',type:'pack'}
];
const quizzes=[{q:'웨이퍼는 무엇으로 만들까?',a:['고순도 실리콘','나무','고무'],c:0},{q:'산화 공정에서 표면에 생기는 것은?',a:['산화막','물방울','금속선'],c:0},{q:'포토 공정에서 빛에 반응하는 물질은?',a:['감광액(PR)','구리선','냉각수'],c:0}];
const processVisuals=[['잉곳','◉','웨이퍼'],['열','♨','산화막'],['빛','✦','회로 패턴'],['식각','⌁','필요 영역'],['원자','◆','박막'],['연결','⌘','배선'],['검사','✓','정상 다이'],['조립','▣','완성 칩']];
let current=0,score=0,states=Array(8).fill(false),timer=null,quizTimer=null,quizPassed=Array(3).fill(false),quizFor=null;
const $=id=>document.getElementById(id);const show=id=>['startScreen','gameScreen','quizScreen','finishScreen'].forEach(x=>$(x).classList.toggle('hidden',x!==id));
function setupList(){ $('stageList').innerHTML=stages.map((s,i)=>`<div class="stage-item ${i===current?'active ':''}${states[i]?'done':''}" onclick="goStage(${i})"><span class="stage-num">${states[i]?'✓':processVisuals[i][1]}</span><span>${s.name}</span></div>`).join('') }
function updateHud(){ $('score').textContent=score;$('progressBar').style.width=(states.filter(Boolean).length/8*100)+'%';$('stageCount').textContent=`MISSION ${current+1} / 8`;setupList() }
function goStage(i){clearInterval(timer);current=i;show('gameScreen');render()}
function start(){clearInterval(timer);current=0;score=0;states=Array(8).fill(false);quizPassed=Array(3).fill(false);show('gameScreen');render()}
function render(){clearInterval(timer);const s=stages[current];updateHud();$('stageEyebrow').textContent=`${s.tag} · NEW MISSION`;$('stageTitle').textContent=s.name;$('stageNo').textContent=String(current+1).padStart(2,'0');$('stageDesc').textContent=s.desc;$('visualGuide').innerHTML=processVisuals[current].map((x,i)=>`<div class="visual-step ${i===1?'active':''}"><div class="visual-icon">${x[1]}</div><span class="visual-label">${x[i===1?2:0]}</span></div>${i<2?'<span class="visual-arrow">→</span>':''}`).join('');$('feedback').textContent='';$('nextBtn').classList.toggle('hidden',!states[current]);$('nextBtn').innerHTML=current===7?'결과 보기 <span>→</span>':'다음 공정 <span>→</span>';const a=$('gameArea');a.innerHTML='';games[s.type](a)}
function complete(msg,points=100){if(states[current]){$('feedback').textContent='이미 클리어한 공정이야. 다른 공정도 도전해 봐!';return}states[current]=true;score+=points;updateHud();$('feedback').textContent=`${msg}  +${points}점`;$('nextBtn').classList.remove('hidden')}
const games={
slice(a){a.innerHTML=`<div class="mission-box slice-box"><h3>초박형 잉곳 직접 절단</h3><p class="mission-tip">칼날을 초록색의 아주 좁은 절단선에 맞춘 뒤, 위에서 아래까지 끌어 내려 잉곳을 얇게 썰어 봐. 조금만 흔들려도 실패해.</p><div class="slice-board" id="sliceBoard"><div class="slice-target-line"></div><div class="ingot-cylinder"></div><div class="slice-blade" id="sliceBlade"><span>칼날</span></div><div class="slice-guide">위에서 시작해서 아래까지 드래그</div></div><div class="slice-readout">절단 정밀도 <b id="slicePrecision">대기 중</b></div><button class="game-btn" id="sliceReset">칼날 놓고 다시 도전</button></div>`;const board=$('sliceBoard');const blade=$('sliceBlade');const precision=$('slicePrecision');let cutting=false,startY=0,progress=0;const fail=()=>{cutting=false;blade.classList.remove('cutting');precision.textContent='절단 실패';precision.className='slice-fail';$('feedback').textContent='칼날이 목표선에서 흔들렸어. 초록색 선에 맞춰 위에서 아래까지 다시 썰어 봐.'};const move=e=>{if(!cutting)return;const r=board.getBoundingClientRect();const x=Math.max(8,Math.min(r.width-8,e.clientX-r.left));const y=Math.max(8,Math.min(r.height-8,e.clientY-r.top));blade.style.left=x+'px';blade.style.top=y+'px';const target=r.width*.5;const error=Math.abs(x-target)/(r.width);progress=Math.max(progress,y/r.height);precision.textContent=Math.round((1-error)*100)+'%';if(error>.01)fail()};blade.onpointerdown=e=>{if(states[current])return;const r=board.getBoundingClientRect();cutting=true;startY=e.clientY-r.top;progress=0;blade.setPointerCapture(e.pointerId);blade.classList.add('cutting');precision.textContent='절단 중';e.preventDefault()};blade.onpointermove=move;blade.onpointerup=()=>{if(!cutting)return;const r=board.getBoundingClientRect();const x=Number.parseFloat(blade.style.left)||0;if(progress>.9&&Math.abs(x-r.width*.5)/r.width<=.01){cutting=false;blade.classList.remove('cutting');precision.textContent='초정밀 성공';precision.className='slice-success';complete('잉곳을 아주 얇고 정밀하게 절단했어! 웨이퍼가 완성됐어!',180)}else fail()};$('sliceReset').onclick=()=>{cutting=false;progress=0;blade.classList.remove('cutting');blade.style.left='50%';blade.style.top='8px';precision.textContent='대기 중';precision.className='';$('feedback').textContent='칼날을 초록색 목표선에 맞춰 위에서 아래로 드래그해.'};$('sliceReset').click();}, 
tune(a){a.innerHTML=`<div class="mission-box"><h3>산화막 리듬 제어</h3><p class="mission-tip">버튼을 여유 있게 일정한 간격으로 눌러 산화로의 리듬을 맞춰 봐. 첫 입력 뒤 약 0.65초 간격으로 7번 눌러야 해.</p><div class="value"><span id="rhythmCount">0</span> / 7</div><button class="game-btn" id="rhythmBtn">리듬 시작</button><button class="sort-btn" id="rhythmReset">다시 도전</button><p id="rhythmReadout" class="mission-tip">준비가 되면 리듬 시작 버튼을 눌러.</p></div>`;const btn=$('rhythmBtn'),reset=$('rhythmReset'),count=$('rhythmCount'),readout=$('rhythmReadout');let hits=0,last=0,playing=false;const target=650,tolerance=220;const stop=()=>{clearInterval(timer);timer=null;playing=false};const fail=msg=>{stop();$('feedback').textContent=msg;readout.textContent='실패했어. 다시 도전 버튼으로 리듬을 맞춰 봐.';btn.disabled=false};const resetGame=()=>{stop();hits=0;last=0;count.textContent='0';readout.textContent='준비가 되면 리듬 시작 버튼을 눌러.';btn.disabled=false;$('feedback').textContent=''};btn.onclick=()=>{if(states[current]||playing)return;const now=performance.now();if(!playing){playing=true;hits=1;last=now;count.textContent='1';btn.textContent='계속 누르기';readout.textContent='좋아! 같은 간격으로 빠르게 눌러!';timer=setInterval(()=>{if(performance.now()-last>target+tolerance)fail('입력이 너무 늦었어. 빠르고 일정한 간격을 유지해야 해.')},40);return}const gap=now-last;if(gap<target-tolerance||gap>target+tolerance){fail('입력 간격이 일정하지 않아. 약 0.65초마다 여유 있게 눌러 봐.');return}last=now;hits++;count.textContent=hits;readout.textContent=`현재 간격 ${Math.round(gap)}ms · 안정적인 리듬이야!`;if(hits===7){stop();btn.disabled=true;complete('빠르고 일정한 리듬으로 산화 공정을 제어했어!',110)}};reset.onclick=resetGame;resetGame()}, 
pattern(a){a.innerHTML=`<div class="mission-box"><h3>마스크 패턴 선택</h3><p class="mission-tip">목표 회로 모양과 같은 마스크를 선택해.</p><div class="pattern-grid"><button class="pattern">＋＋<br>＋＋</button><button class="pattern">╲╱<br>╱╲</button><button class="pattern" data-ok="1">┼<br>┼</button><button class="pattern">○ ○<br>○ ○</button><button class="pattern">━━<br>━━</button><button class="pattern">△△<br>▽▽</button></div></div>`;a.querySelectorAll('.pattern').forEach(b=>b.onclick=()=>b.dataset.ok?complete('회로 패턴을 정확히 노광했어!',120):$('feedback').textContent='패턴이 목표 회로와 달라. 다시 살펴봐!')},
etch(a){const marked=[1,3,5,7,9,11,13,15,17];a.innerHTML=`<div class="mission-box"><h3>보호되지 않은 영역 제거</h3><p class="mission-tip">분홍색으로 표시된 9칸만 클릭해서 식각해.</p><div class="etch-grid" id="etchGrid"></div></div>`;let hit=0,g=$('etchGrid');for(let i=0;i<25;i++){let b=document.createElement('button');b.className='etch-cell';if(marked.includes(i))b.classList.add('marked');b.onclick=()=>{if(!marked.includes(i)){$('feedback').textContent='보호막까지 깎였어! 다른 칸을 골라 봐.';return}if(b.disabled)return;b.disabled=true;b.style.opacity='.35';hit++;if(hit===9)complete('필요한 영역만 깔끔하게 식각했어!',125)};g.append(b)}},
balance(a){a.innerHTML=`<div class="mission-box"><h3>원자 공급 균형</h3><p class="mission-tip">왼쪽과 오른쪽 원자를 조절해 두 값의 차이를 0으로 만들어.</p><div class="scale"><div class="pan">A 원자<br><b id="leftVal">3</b></div><div class="pan">B 원자<br><b id="rightVal">1</b></div></div><div class="controls"><button class="game-btn" id="leftAdd">A 주입 +</button><button class="game-btn" id="rightAdd">B 주입 +</button></div></div>`;let l=3,r=1;$('leftAdd').onclick=()=>{l++;$('leftVal').textContent=l};$('rightAdd').onclick=()=>{r++;$('rightVal').textContent=r;if(l===r)complete('원자 비율이 균형을 이뤘어! 균일한 박막 완성!',135)}},
connect(a){a.innerHTML=`<div class="mission-box"><h3>접점 연결 네트워크</h3><p class="mission-tip">1번부터 6번까지 이어지는 접점을 올바른 순서로 눌러.</p><div class="node-grid" id="nodes"></div></div>`;let n=1,g=$('nodes');for(let i=1;i<=8;i++){let b=document.createElement('button');b.className='node';b.textContent=i;b.onclick=()=>{if(i===n){b.classList.add('linked');b.disabled=true;n++;if(n===7)complete('전류가 흐르는 금속 배선을 연결했어!',130)}else{$('feedback').textContent='접점 순서가 끊겼어. 1번부터 다시 시작해!';n=1;g.querySelectorAll('button').forEach(x=>{x.disabled=false;x.classList.remove('linked')})}};g.append(b)}},
sort(a){a.innerHTML=`<div class="mission-box"><h3>EDS 불량 판정</h3><p class="mission-tip">검사 카드를 읽고 정상 또는 불량으로 판정해. 5장을 맞히면 성공이야.</p><div class="defect-card"><b id="cardTitle">검사 중...</b><p id="cardData"></p><button class="sort-btn" id="normal">정상</button><button class="sort-btn" id="bad">불량</button></div><p id="sortCount" class="mission-score">판정 0 / 5</p></div>`;let cards=[true,false,true,false,false],n=0;function next(){if(n===5)return;$('cardTitle').textContent=`다이 #${n+1}`;$('cardData').textContent=cards[n]?'전기 신호 안정 · 흠집 없음':'전기 신호 불안정 · 미세 균열 발견'}function judge(v){if(v!==cards[n]){$('feedback').textContent='판정이 틀렸어. 측정 결과를 다시 읽어 봐!';return}n++;$('sortCount').textContent=`판정 ${n} / 5`;n===5?complete('불량 다이를 정확히 분류했어!',145):next()}$('normal').onclick=()=>judge(true);$('bad').onclick=()=>judge(false);next()},
pack(a){a.innerHTML=`<div class="mission-box"><h3>패키지 부품 조립</h3><p class="mission-tip">부품 버튼과 같은 모양의 슬롯을 찾아 짝을 맞춰. 4쌍을 완성해!</p><div class="choice-grid" id="parts"><button class="choice" data-p="칩">칩</button><button class="choice" data-p="핀">핀</button><button class="choice" data-p="뚜껑">뚜껑</button><button class="choice" data-p="방열판">방열판</button></div><div class="package" id="slots"><button class="package-slot" data-p="방열판">?</button><button class="package-slot" data-p="칩">?</button><button class="package-slot" data-p="뚜껑">?</button><button class="package-slot" data-p="핀">?</button></div></div>`;let selected=null,hit=0;a.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{if(b.classList.contains('filled'))return;if(b.classList.contains('choice')){selected=b.dataset.p;a.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('feedback').textContent=`${selected} 부품을 선택했어. 같은 슬롯을 눌러!`}else if(selected===b.dataset.p){b.textContent=selected;b.classList.add('filled');hit++;selected=null;if(hit===4)complete('모든 부품을 안전하게 패키징했어!',160)}else $('feedback').textContent='부품 모양과 슬롯이 달라!'} )}
};
function nextStage(){if(!states[current]){ $('feedback').textContent='먼저 이 공정의 미션을 성공해야 다음으로 갈 수 있어.';return}if(current===7){finish();return}if(current===2||current===5){quizFor=current;showQuiz();return}current++;render()}
function showQuiz(){clearTimeout(quizTimer);const quizStage=quizFor;const q=quizzes[quizStage===2?1:2];$('quizQuestion').textContent=q.q;$('quizFeedback').textContent='';$('quizOptions').innerHTML=q.a.map((x,i)=>`<button class="quiz-option">${String.fromCharCode(65+i)}. ${x}</button>`).join('');document.querySelectorAll('.quiz-option').forEach((b,i)=>b.onclick=()=>{if(i!==q.c){$('quizFeedback').textContent='다시 생각해 봐! 공정 설명을 떠올려 봐.';return}if(!quizPassed[quizStage===2?1:2]){score+=50;quizPassed[quizStage===2?1:2]=true;$('score').textContent=score}$('quizFeedback').textContent='정답! +50점';document.querySelectorAll('.quiz-option').forEach(option=>option.disabled=true);quizTimer=setTimeout(()=>{current=quizStage+1;show('gameScreen');render()},500)})}
function finish(){clearInterval(timer);$('finalScore').textContent=score;$('finishSummary').textContent=`성공 ${states.filter(Boolean).length}개 · 아직 완료하지 않은 공정 ${states.filter(x=>!x).length}개 · 메뉴에서 언제든 다시 도전할 수 있어.`;$('stageCount').textContent='MISSION REPORT';show('finishScreen')}
$('startBtn').onclick=start;$('restartBtn').onclick=start;$('nextBtn').onclick=nextStage;show('startScreen');